# Generated by Django 2.2.6 on 2022-10-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221018_2149'),
        ('posts', '0006_auto_20221027_0144'),
    ]

    operations = [
    ]
